package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Bloodtest generated by hbm2java
 */
public class Bloodtest implements java.io.Serializable {

	private int bloodTestId;
	private String bloodTestReport;
	private Integer emrId;
	private String date;
	private String time;

	public Bloodtest() {
	}

	public Bloodtest(int bloodTestId) {
		this.bloodTestId = bloodTestId;
	}

	public Bloodtest(int bloodTestId, String bloodTestReport, Integer emrId, String date, String time) {
		this.bloodTestId = bloodTestId;
		this.bloodTestReport = bloodTestReport;
		this.emrId = emrId;
		this.date = date;
		this.time = time;
	}

	public int getBloodTestId() {
		return this.bloodTestId;
	}

	public void setBloodTestId(int bloodTestId) {
		this.bloodTestId = bloodTestId;
	}

	public String getBloodTestReport() {
		return this.bloodTestReport;
	}

	public void setBloodTestReport(String bloodTestReport) {
		this.bloodTestReport = bloodTestReport;
	}

	public Integer getEmrId() {
		return this.emrId;
	}

	public void setEmrId(Integer emrId) {
		this.emrId = emrId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

}
