package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Department generated by hbm2java
 */
public class Department implements java.io.Serializable {

	private int departmentId;
	private String department;

	public Department() {
	}

	public Department(int departmentId) {
		this.departmentId = departmentId;
	}

	public Department(int departmentId, String department) {
		this.departmentId = departmentId;
		this.department = department;
	}

	public int getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(int departmentId) {
		this.departmentId = departmentId;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

}
