package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Disease generated by hbm2java
 */
public class Disease implements java.io.Serializable {

	private int id;
	private String diseaseName;
	private String cause;
	private String tests;
	private String vaccines;
	private String otherDetails;

	public Disease() {
	}

	public Disease(int id) {
		this.id = id;
	}

	public Disease(int id, String diseaseName, String cause, String tests, String vaccines, String otherDetails) {
		this.id = id;
		this.diseaseName = diseaseName;
		this.cause = cause;
		this.tests = tests;
		this.vaccines = vaccines;
		this.otherDetails = otherDetails;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getDiseaseName() {
		return this.diseaseName;
	}

	public void setDiseaseName(String diseaseName) {
		this.diseaseName = diseaseName;
	}

	public String getCause() {
		return this.cause;
	}

	public void setCause(String cause) {
		this.cause = cause;
	}

	public String getTests() {
		return this.tests;
	}

	public void setTests(String tests) {
		this.tests = tests;
	}

	public String getVaccines() {
		return this.vaccines;
	}

	public void setVaccines(String vaccines) {
		this.vaccines = vaccines;
	}

	public String getOtherDetails() {
		return this.otherDetails;
	}

	public void setOtherDetails(String otherDetails) {
		this.otherDetails = otherDetails;
	}

}
