package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Doctorsinhospital generated by hbm2java
 */
public class Doctorsinhospital implements java.io.Serializable {

	private DoctorsinhospitalId id;

	public Doctorsinhospital() {
	}

	public Doctorsinhospital(DoctorsinhospitalId id) {
		this.id = id;
	}

	public DoctorsinhospitalId getId() {
		return this.id;
	}

	public void setId(DoctorsinhospitalId id) {
		this.id = id;
	}

}
