package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Doctorinfo generated by hbm2java
 */
public class Doctorinfo implements java.io.Serializable {

	private int doctorId;
	private int userId;
	private String doctorsDescription;

	public Doctorinfo() {
	}

	public Doctorinfo(int doctorId, int userId) {
		this.doctorId = doctorId;
		this.userId = userId;
	}

	public Doctorinfo(int doctorId, int userId, String doctorsDescription) {
		this.doctorId = doctorId;
		this.userId = userId;
		this.doctorsDescription = doctorsDescription;
	}

	public int getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(int doctorId) {
		this.doctorId = doctorId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public String getDoctorsDescription() {
		return this.doctorsDescription;
	}

	public void setDoctorsDescription(String doctorsDescription) {
		this.doctorsDescription = doctorsDescription;
	}

}
