package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Doctorsspeciality generated by hbm2java
 */
public class Doctorsspeciality implements java.io.Serializable {

	private DoctorsspecialityId id;

	public Doctorsspeciality() {
	}

	public Doctorsspeciality(DoctorsspecialityId id) {
		this.id = id;
	}

	public DoctorsspecialityId getId() {
		return this.id;
	}

	public void setId(DoctorsspecialityId id) {
		this.id = id;
	}

}
