package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ElectronicMedicalRecord generated by hbm2java
 */
public class ElectronicMedicalRecord implements java.io.Serializable {

	private int emrid;
	private int userId;

	public ElectronicMedicalRecord() {
	}

	public ElectronicMedicalRecord(int emrid, int userId) {
		this.emrid = emrid;
		this.userId = userId;
	}

	public int getEmrid() {
		return this.emrid;
	}

	public void setEmrid(int emrid) {
		this.emrid = emrid;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

}
