package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ElectronicMedicalRecord generated by hbm2java
 */
public class ElectronicMedicalRecord implements java.io.Serializable {

	private ElectronicMedicalRecordId id;

	public ElectronicMedicalRecord() {
	}

	public ElectronicMedicalRecord(ElectronicMedicalRecordId id) {
		this.id = id;
	}

	public ElectronicMedicalRecordId getId() {
		return this.id;
	}

	public void setId(ElectronicMedicalRecordId id) {
		this.id = id;
	}

}
