package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * ElectronicMedicalRecordId generated by hbm2java
 */
public class ElectronicMedicalRecordId implements java.io.Serializable {

	private int emrid;
	private int userId;

	public ElectronicMedicalRecordId() {
	}

	public ElectronicMedicalRecordId(int emrid, int userId) {
		this.emrid = emrid;
		this.userId = userId;
	}

	public int getEmrid() {
		return this.emrid;
	}

	public void setEmrid(int emrid) {
		this.emrid = emrid;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ElectronicMedicalRecordId))
			return false;
		ElectronicMedicalRecordId castOther = (ElectronicMedicalRecordId) other;

		return (this.getEmrid() == castOther.getEmrid()) && (this.getUserId() == castOther.getUserId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEmrid();
		result = 37 * result + this.getUserId();
		return result;
	}

}
