package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Familyrelation generated by hbm2java
 */
public class Familyrelation implements java.io.Serializable {

	private int familyId;
	private int user1;
	private int user2;
	private int relationshipTypeId;

	public Familyrelation() {
	}

	public Familyrelation(int familyId, int user1, int user2, int relationshipTypeId) {
		this.familyId = familyId;
		this.user1 = user1;
		this.user2 = user2;
		this.relationshipTypeId = relationshipTypeId;
	}

	public int getFamilyId() {
		return this.familyId;
	}

	public void setFamilyId(int familyId) {
		this.familyId = familyId;
	}

	public int getUser1() {
		return this.user1;
	}

	public void setUser1(int user1) {
		this.user1 = user1;
	}

	public int getUser2() {
		return this.user2;
	}

	public void setUser2(int user2) {
		this.user2 = user2;
	}

	public int getRelationshipTypeId() {
		return this.relationshipTypeId;
	}

	public void setRelationshipTypeId(int relationshipTypeId) {
		this.relationshipTypeId = relationshipTypeId;
	}

}
