package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Familyrelation generated by hbm2java
 */
public class Familyrelation implements java.io.Serializable {

	private FamilyrelationId id;

	public Familyrelation() {
	}

	public Familyrelation(FamilyrelationId id) {
		this.id = id;
	}

	public FamilyrelationId getId() {
		return this.id;
	}

	public void setId(FamilyrelationId id) {
		this.id = id;
	}

}
