package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Generalhealthcheckupdetails generated by hbm2java
 */
public class Generalhealthcheckupdetails implements java.io.Serializable {

	private GeneralhealthcheckupdetailsId id;

	public Generalhealthcheckupdetails() {
	}

	public Generalhealthcheckupdetails(GeneralhealthcheckupdetailsId id) {
		this.id = id;
	}

	public GeneralhealthcheckupdetailsId getId() {
		return this.id;
	}

	public void setId(GeneralhealthcheckupdetailsId id) {
		this.id = id;
	}

}
