package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * GeneralhealthcheckupdetailsId generated by hbm2java
 */
public class GeneralhealthcheckupdetailsId implements java.io.Serializable {

	private Integer id;
	private String bloodPressureLevels;
	private String sugarLevel;
	private String bodyTemperature;
	private String pulseRate;
	private Boolean pregnencyStatus;
	private Integer weight;
	private Integer height;
	private Integer interactionInteractionId;

	public GeneralhealthcheckupdetailsId() {
	}

	public GeneralhealthcheckupdetailsId(Integer id, String bloodPressureLevels, String sugarLevel,
			String bodyTemperature, String pulseRate, Boolean pregnencyStatus, Integer weight, Integer height,
			Integer interactionInteractionId) {
		this.id = id;
		this.bloodPressureLevels = bloodPressureLevels;
		this.sugarLevel = sugarLevel;
		this.bodyTemperature = bodyTemperature;
		this.pulseRate = pulseRate;
		this.pregnencyStatus = pregnencyStatus;
		this.weight = weight;
		this.height = height;
		this.interactionInteractionId = interactionInteractionId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getBloodPressureLevels() {
		return this.bloodPressureLevels;
	}

	public void setBloodPressureLevels(String bloodPressureLevels) {
		this.bloodPressureLevels = bloodPressureLevels;
	}

	public String getSugarLevel() {
		return this.sugarLevel;
	}

	public void setSugarLevel(String sugarLevel) {
		this.sugarLevel = sugarLevel;
	}

	public String getBodyTemperature() {
		return this.bodyTemperature;
	}

	public void setBodyTemperature(String bodyTemperature) {
		this.bodyTemperature = bodyTemperature;
	}

	public String getPulseRate() {
		return this.pulseRate;
	}

	public void setPulseRate(String pulseRate) {
		this.pulseRate = pulseRate;
	}

	public Boolean getPregnencyStatus() {
		return this.pregnencyStatus;
	}

	public void setPregnencyStatus(Boolean pregnencyStatus) {
		this.pregnencyStatus = pregnencyStatus;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public Integer getInteractionInteractionId() {
		return this.interactionInteractionId;
	}

	public void setInteractionInteractionId(Integer interactionInteractionId) {
		this.interactionInteractionId = interactionInteractionId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GeneralhealthcheckupdetailsId))
			return false;
		GeneralhealthcheckupdetailsId castOther = (GeneralhealthcheckupdetailsId) other;

		return ((this.getId() == castOther.getId())
				|| (this.getId() != null && castOther.getId() != null && this.getId().equals(castOther.getId())))
				&& ((this.getBloodPressureLevels() == castOther.getBloodPressureLevels())
						|| (this.getBloodPressureLevels() != null && castOther.getBloodPressureLevels() != null
								&& this.getBloodPressureLevels().equals(castOther.getBloodPressureLevels())))
				&& ((this.getSugarLevel() == castOther.getSugarLevel()) || (this.getSugarLevel() != null
						&& castOther.getSugarLevel() != null && this.getSugarLevel().equals(castOther.getSugarLevel())))
				&& ((this.getBodyTemperature() == castOther.getBodyTemperature())
						|| (this.getBodyTemperature() != null && castOther.getBodyTemperature() != null
								&& this.getBodyTemperature().equals(castOther.getBodyTemperature())))
				&& ((this.getPulseRate() == castOther.getPulseRate()) || (this.getPulseRate() != null
						&& castOther.getPulseRate() != null && this.getPulseRate().equals(castOther.getPulseRate())))
				&& ((this.getPregnencyStatus() == castOther.getPregnencyStatus())
						|| (this.getPregnencyStatus() != null && castOther.getPregnencyStatus() != null
								&& this.getPregnencyStatus().equals(castOther.getPregnencyStatus())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null
						&& castOther.getHeight() != null && this.getHeight().equals(castOther.getHeight())))
				&& ((this.getInteractionInteractionId() == castOther.getInteractionInteractionId())
						|| (this.getInteractionInteractionId() != null
								&& castOther.getInteractionInteractionId() != null
								&& this.getInteractionInteractionId().equals(castOther.getInteractionInteractionId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result + (getBloodPressureLevels() == null ? 0 : this.getBloodPressureLevels().hashCode());
		result = 37 * result + (getSugarLevel() == null ? 0 : this.getSugarLevel().hashCode());
		result = 37 * result + (getBodyTemperature() == null ? 0 : this.getBodyTemperature().hashCode());
		result = 37 * result + (getPulseRate() == null ? 0 : this.getPulseRate().hashCode());
		result = 37 * result + (getPregnencyStatus() == null ? 0 : this.getPregnencyStatus().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result
				+ (getInteractionInteractionId() == null ? 0 : this.getInteractionInteractionId().hashCode());
		return result;
	}

}
