package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Healthmanagertopatient generated by hbm2java
 */
public class Healthmanagertopatient implements java.io.Serializable {

	private HealthmanagertopatientId id;

	public Healthmanagertopatient() {
	}

	public Healthmanagertopatient(HealthmanagertopatientId id) {
		this.id = id;
	}

	public HealthmanagertopatientId getId() {
		return this.id;
	}

	public void setId(HealthmanagertopatientId id) {
		this.id = id;
	}

}
