package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * HospitaldepartmentrecordId generated by hbm2java
 */
public class HospitaldepartmentrecordId implements java.io.Serializable {

	private int hospitalId;
	private int doctorInfoDoctorId;

	public HospitaldepartmentrecordId() {
	}

	public HospitaldepartmentrecordId(int hospitalId, int doctorInfoDoctorId) {
		this.hospitalId = hospitalId;
		this.doctorInfoDoctorId = doctorInfoDoctorId;
	}

	public int getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(int hospitalId) {
		this.hospitalId = hospitalId;
	}

	public int getDoctorInfoDoctorId() {
		return this.doctorInfoDoctorId;
	}

	public void setDoctorInfoDoctorId(int doctorInfoDoctorId) {
		this.doctorInfoDoctorId = doctorInfoDoctorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospitaldepartmentrecordId))
			return false;
		HospitaldepartmentrecordId castOther = (HospitaldepartmentrecordId) other;

		return (this.getHospitalId() == castOther.getHospitalId())
				&& (this.getDoctorInfoDoctorId() == castOther.getDoctorInfoDoctorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHospitalId();
		result = 37 * result + this.getDoctorInfoDoctorId();
		return result;
	}

}
