package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * HospitalspecialityId generated by hbm2java
 */
public class HospitalspecialityId implements java.io.Serializable {

	private int hospitalid;
	private int specialityId;

	public HospitalspecialityId() {
	}

	public HospitalspecialityId(int hospitalid, int specialityId) {
		this.hospitalid = hospitalid;
		this.specialityId = specialityId;
	}

	public int getHospitalid() {
		return this.hospitalid;
	}

	public void setHospitalid(int hospitalid) {
		this.hospitalid = hospitalid;
	}

	public int getSpecialityId() {
		return this.specialityId;
	}

	public void setSpecialityId(int specialityId) {
		this.specialityId = specialityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HospitalspecialityId))
			return false;
		HospitalspecialityId castOther = (HospitalspecialityId) other;

		return (this.getHospitalid() == castOther.getHospitalid())
				&& (this.getSpecialityId() == castOther.getSpecialityId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getHospitalid();
		result = 37 * result + this.getSpecialityId();
		return result;
	}

}
