package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Hospitalspeciality generated by hbm2java
 */
public class Hospitalspeciality implements java.io.Serializable {

	private HospitalspecialityId id;

	public Hospitalspeciality() {
	}

	public Hospitalspeciality(HospitalspecialityId id) {
		this.id = id;
	}

	public HospitalspecialityId getId() {
		return this.id;
	}

	public void setId(HospitalspecialityId id) {
		this.id = id;
	}

}
