package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * InteractiontestrecordId generated by hbm2java
 */
public class InteractiontestrecordId implements java.io.Serializable {

	private int interactionId;
	private Integer testId;

	public InteractiontestrecordId() {
	}

	public InteractiontestrecordId(int interactionId) {
		this.interactionId = interactionId;
	}

	public InteractiontestrecordId(int interactionId, Integer testId) {
		this.interactionId = interactionId;
		this.testId = testId;
	}

	public int getInteractionId() {
		return this.interactionId;
	}

	public void setInteractionId(int interactionId) {
		this.interactionId = interactionId;
	}

	public Integer getTestId() {
		return this.testId;
	}

	public void setTestId(Integer testId) {
		this.testId = testId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InteractiontestrecordId))
			return false;
		InteractiontestrecordId castOther = (InteractiontestrecordId) other;

		return (this.getInteractionId() == castOther.getInteractionId())
				&& ((this.getTestId() == castOther.getTestId()) || (this.getTestId() != null
						&& castOther.getTestId() != null && this.getTestId().equals(castOther.getTestId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getInteractionId();
		result = 37 * result + (getTestId() == null ? 0 : this.getTestId().hashCode());
		return result;
	}

}
