package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Interactiontestrecord generated by hbm2java
 */
public class Interactiontestrecord implements java.io.Serializable {

	private InteractiontestrecordId id;

	public Interactiontestrecord() {
	}

	public Interactiontestrecord(InteractiontestrecordId id) {
		this.id = id;
	}

	public InteractiontestrecordId getId() {
		return this.id;
	}

	public void setId(InteractiontestrecordId id) {
		this.id = id;
	}

}
