package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Jobrole generated by hbm2java
 */
public class Jobrole implements java.io.Serializable {

	private int jobRoleId;
	private String jobRoll;

	public Jobrole() {
	}

	public Jobrole(int jobRoleId, String jobRoll) {
		this.jobRoleId = jobRoleId;
		this.jobRoll = jobRoll;
	}

	public int getJobRoleId() {
		return this.jobRoleId;
	}

	public void setJobRoleId(int jobRoleId) {
		this.jobRoleId = jobRoleId;
	}

	public String getJobRoll() {
		return this.jobRoll;
	}

	public void setJobRoll(String jobRoll) {
		this.jobRoll = jobRoll;
	}

}
