package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Logincredentails generated by hbm2java
 */
public class Logincredentails implements java.io.Serializable {

	private LogincredentailsId id;

	public Logincredentails() {
	}

	public Logincredentails(LogincredentailsId id) {
		this.id = id;
	}

	public LogincredentailsId getId() {
		return this.id;
	}

	public void setId(LogincredentailsId id) {
		this.id = id;
	}

}
