package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Medicationroutine generated by hbm2java
 */
public class Medicationroutine implements java.io.Serializable {

	private int id;
	private String routine;

	public Medicationroutine() {
	}

	public Medicationroutine(int id) {
		this.id = id;
	}

	public Medicationroutine(int id, String routine) {
		this.id = id;
		this.routine = routine;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getRoutine() {
		return this.routine;
	}

	public void setRoutine(String routine) {
		this.routine = routine;
	}

}
