package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Relationtype generated by hbm2java
 */
public class Relationtype implements java.io.Serializable {

	private int relationshipTypeId;
	private String relationship;

	public Relationtype() {
	}

	public Relationtype(int relationshipTypeId) {
		this.relationshipTypeId = relationshipTypeId;
	}

	public Relationtype(int relationshipTypeId, String relationship) {
		this.relationshipTypeId = relationshipTypeId;
		this.relationship = relationship;
	}

	public int getRelationshipTypeId() {
		return this.relationshipTypeId;
	}

	public void setRelationshipTypeId(int relationshipTypeId) {
		this.relationshipTypeId = relationshipTypeId;
	}

	public String getRelationship() {
		return this.relationship;
	}

	public void setRelationship(String relationship) {
		this.relationship = relationship;
	}

}
