package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * SymptomsId generated by hbm2java
 */
public class SymptomsId implements java.io.Serializable {

	private String symptoms;
	private String description;
	private int diseaseId;

	public SymptomsId() {
	}

	public SymptomsId(int diseaseId) {
		this.diseaseId = diseaseId;
	}

	public SymptomsId(String symptoms, String description, int diseaseId) {
		this.symptoms = symptoms;
		this.description = description;
		this.diseaseId = diseaseId;
	}

	public String getSymptoms() {
		return this.symptoms;
	}

	public void setSymptoms(String symptoms) {
		this.symptoms = symptoms;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getDiseaseId() {
		return this.diseaseId;
	}

	public void setDiseaseId(int diseaseId) {
		this.diseaseId = diseaseId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SymptomsId))
			return false;
		SymptomsId castOther = (SymptomsId) other;

		return ((this.getSymptoms() == castOther.getSymptoms()) || (this.getSymptoms() != null
				&& castOther.getSymptoms() != null && this.getSymptoms().equals(castOther.getSymptoms())))
				&& ((this.getDescription() == castOther.getDescription())
						|| (this.getDescription() != null && castOther.getDescription() != null
								&& this.getDescription().equals(castOther.getDescription())))
				&& (this.getDiseaseId() == castOther.getDiseaseId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSymptoms() == null ? 0 : this.getSymptoms().hashCode());
		result = 37 * result + (getDescription() == null ? 0 : this.getDescription().hashCode());
		result = 37 * result + this.getDiseaseId();
		return result;
	}

}
