package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Symptoms generated by hbm2java
 */
public class Symptoms implements java.io.Serializable {

	private SymptomsId id;

	public Symptoms() {
	}

	public Symptoms(SymptomsId id) {
		this.id = id;
	}

	public SymptomsId getId() {
		return this.id;
	}

	public void setId(SymptomsId id) {
		this.id = id;
	}

}
