package mprofile.core.entity;
// Generated Sep 25, 2016 7:14:32 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Urinetest generated by hbm2java
 */
public class Urinetest implements java.io.Serializable {

	private int urineTestId;
	private String testDate;
	private String appearance;
	private String reactions;
	private String albumini;
	private String sugar;
	private String rbcsHpe;
	private String spermatozoa;
	private String totalValue;
	private String date;
	private String time;
	private String report;

	public Urinetest() {
	}

	public Urinetest(int urineTestId) {
		this.urineTestId = urineTestId;
	}

	public Urinetest(int urineTestId, String testDate, String appearance, String reactions, String albumini,
			String sugar, String rbcsHpe, String spermatozoa, String totalValue, String date, String time,
			String report) {
		this.urineTestId = urineTestId;
		this.testDate = testDate;
		this.appearance = appearance;
		this.reactions = reactions;
		this.albumini = albumini;
		this.sugar = sugar;
		this.rbcsHpe = rbcsHpe;
		this.spermatozoa = spermatozoa;
		this.totalValue = totalValue;
		this.date = date;
		this.time = time;
		this.report = report;
	}

	public int getUrineTestId() {
		return this.urineTestId;
	}

	public void setUrineTestId(int urineTestId) {
		this.urineTestId = urineTestId;
	}

	public String getTestDate() {
		return this.testDate;
	}

	public void setTestDate(String testDate) {
		this.testDate = testDate;
	}

	public String getAppearance() {
		return this.appearance;
	}

	public void setAppearance(String appearance) {
		this.appearance = appearance;
	}

	public String getReactions() {
		return this.reactions;
	}

	public void setReactions(String reactions) {
		this.reactions = reactions;
	}

	public String getAlbumini() {
		return this.albumini;
	}

	public void setAlbumini(String albumini) {
		this.albumini = albumini;
	}

	public String getSugar() {
		return this.sugar;
	}

	public void setSugar(String sugar) {
		this.sugar = sugar;
	}

	public String getRbcsHpe() {
		return this.rbcsHpe;
	}

	public void setRbcsHpe(String rbcsHpe) {
		this.rbcsHpe = rbcsHpe;
	}

	public String getSpermatozoa() {
		return this.spermatozoa;
	}

	public void setSpermatozoa(String spermatozoa) {
		this.spermatozoa = spermatozoa;
	}

	public String getTotalValue() {
		return this.totalValue;
	}

	public void setTotalValue(String totalValue) {
		this.totalValue = totalValue;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public String getReport() {
		return this.report;
	}

	public void setReport(String report) {
		this.report = report;
	}

}
