package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Userinfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private UserinfoId id;

	public UserInfo() {
	}

	public UserInfo(UserinfoId id) {
		this.id = id;
	}

	public UserinfoId getId() {
		return this.id;
	}

	public void setId(UserinfoId id) {
		this.id = id;
	}

}
