package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * UserinfoId generated by hbm2java
 */
public class UserinfoId implements java.io.Serializable {

	private int id;
	private String name;
	private String dob;
	private String gender;
	private Integer weight;
	private Integer height;
	private String address;
	private Integer pincode;
	private String city;
	private String country;
	private String emailId;
	private Integer phone;
	private Integer emergencyPhone;
	private String dateOfRegistration;
	private String bloodGroup;

	public UserinfoId() {
	}

	public UserinfoId(int id) {
		this.id = id;
	}

	public UserinfoId(int id, String name, String dob, String gender, Integer weight, Integer height, String address,
			Integer pincode, String city, String country, String emailId, Integer phone, Integer emergencyPhone,
			String dateOfRegistration, String bloodGroup) {
		this.id = id;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.weight = weight;
		this.height = height;
		this.address = address;
		this.pincode = pincode;
		this.city = city;
		this.country = country;
		this.emailId = emailId;
		this.phone = phone;
		this.emergencyPhone = emergencyPhone;
		this.dateOfRegistration = dateOfRegistration;
		this.bloodGroup = bloodGroup;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Integer getWeight() {
		return this.weight;
	}

	public void setWeight(Integer weight) {
		this.weight = weight;
	}

	public Integer getHeight() {
		return this.height;
	}

	public void setHeight(Integer height) {
		this.height = height;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public Integer getPhone() {
		return this.phone;
	}

	public void setPhone(Integer phone) {
		this.phone = phone;
	}

	public Integer getEmergencyPhone() {
		return this.emergencyPhone;
	}

	public void setEmergencyPhone(Integer emergencyPhone) {
		this.emergencyPhone = emergencyPhone;
	}

	public String getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(String dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserinfoId))
			return false;
		UserinfoId castOther = (UserinfoId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())))
				&& ((this.getDob() == castOther.getDob()) || (this.getDob() != null && castOther.getDob() != null
						&& this.getDob().equals(castOther.getDob())))
				&& ((this.getGender() == castOther.getGender()) || (this.getGender() != null
						&& castOther.getGender() != null && this.getGender().equals(castOther.getGender())))
				&& ((this.getWeight() == castOther.getWeight()) || (this.getWeight() != null
						&& castOther.getWeight() != null && this.getWeight().equals(castOther.getWeight())))
				&& ((this.getHeight() == castOther.getHeight()) || (this.getHeight() != null
						&& castOther.getHeight() != null && this.getHeight().equals(castOther.getHeight())))
				&& ((this.getAddress() == castOther.getAddress()) || (this.getAddress() != null
						&& castOther.getAddress() != null && this.getAddress().equals(castOther.getAddress())))
				&& ((this.getPincode() == castOther.getPincode()) || (this.getPincode() != null
						&& castOther.getPincode() != null && this.getPincode().equals(castOther.getPincode())))
				&& ((this.getCity() == castOther.getCity()) || (this.getCity() != null && castOther.getCity() != null
						&& this.getCity().equals(castOther.getCity())))
				&& ((this.getCountry() == castOther.getCountry()) || (this.getCountry() != null
						&& castOther.getCountry() != null && this.getCountry().equals(castOther.getCountry())))
				&& ((this.getEmailId() == castOther.getEmailId()) || (this.getEmailId() != null
						&& castOther.getEmailId() != null && this.getEmailId().equals(castOther.getEmailId())))
				&& ((this.getPhone() == castOther.getPhone()) || (this.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone().equals(castOther.getPhone())))
				&& ((this.getEmergencyPhone() == castOther.getEmergencyPhone())
						|| (this.getEmergencyPhone() != null && castOther.getEmergencyPhone() != null
								&& this.getEmergencyPhone().equals(castOther.getEmergencyPhone())))
				&& ((this.getDateOfRegistration() == castOther.getDateOfRegistration())
						|| (this.getDateOfRegistration() != null && castOther.getDateOfRegistration() != null
								&& this.getDateOfRegistration().equals(castOther.getDateOfRegistration())))
				&& ((this.getBloodGroup() == castOther.getBloodGroup())
						|| (this.getBloodGroup() != null && castOther.getBloodGroup() != null
								&& this.getBloodGroup().equals(castOther.getBloodGroup())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + (getDob() == null ? 0 : this.getDob().hashCode());
		result = 37 * result + (getGender() == null ? 0 : this.getGender().hashCode());
		result = 37 * result + (getWeight() == null ? 0 : this.getWeight().hashCode());
		result = 37 * result + (getHeight() == null ? 0 : this.getHeight().hashCode());
		result = 37 * result + (getAddress() == null ? 0 : this.getAddress().hashCode());
		result = 37 * result + (getPincode() == null ? 0 : this.getPincode().hashCode());
		result = 37 * result + (getCity() == null ? 0 : this.getCity().hashCode());
		result = 37 * result + (getCountry() == null ? 0 : this.getCountry().hashCode());
		result = 37 * result + (getEmailId() == null ? 0 : this.getEmailId().hashCode());
		result = 37 * result + (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result + (getEmergencyPhone() == null ? 0 : this.getEmergencyPhone().hashCode());
		result = 37 * result + (getDateOfRegistration() == null ? 0 : this.getDateOfRegistration().hashCode());
		result = 37 * result + (getBloodGroup() == null ? 0 : this.getBloodGroup().hashCode());
		return result;
	}

}
