package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private int id;
	private String name;
	private String dob;
	private String gender;
	private int weight;
	private int height;
	private String address;
	private int pincode;
	private String city;
	private String country;
	private String emailId;
	private int phone;
	private Integer emergencyPhone;
	private String dateOfRegistration;
	private String bloodGroup;
	private Integer familyRelationFamilyId;

	public UserInfo() {
	}

	public UserInfo(int id, String name, String dob, String gender, int weight, int height, String address, int pincode,
			String city, String country, String emailId, int phone, String bloodGroup) {
		this.id = id;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.weight = weight;
		this.height = height;
		this.address = address;
		this.pincode = pincode;
		this.city = city;
		this.country = country;
		this.emailId = emailId;
		this.phone = phone;
		this.bloodGroup = bloodGroup;
	}

	public UserInfo(int id, String name, String dob, String gender, int weight, int height, String address, int pincode,
			String city, String country, String emailId, int phone, Integer emergencyPhone, String dateOfRegistration,
			String bloodGroup, Integer familyRelationFamilyId) {
		this.id = id;
		this.name = name;
		this.dob = dob;
		this.gender = gender;
		this.weight = weight;
		this.height = height;
		this.address = address;
		this.pincode = pincode;
		this.city = city;
		this.country = country;
		this.emailId = emailId;
		this.phone = phone;
		this.emergencyPhone = emergencyPhone;
		this.dateOfRegistration = dateOfRegistration;
		this.bloodGroup = bloodGroup;
		this.familyRelationFamilyId = familyRelationFamilyId;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDob() {
		return this.dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public int getWeight() {
		return this.weight;
	}

	public void setWeight(int weight) {
		this.weight = weight;
	}

	public int getHeight() {
		return this.height;
	}

	public void setHeight(int height) {
		this.height = height;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getPincode() {
		return this.pincode;
	}

	public void setPincode(int pincode) {
		this.pincode = pincode;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	public int getPhone() {
		return this.phone;
	}

	public void setPhone(int phone) {
		this.phone = phone;
	}

	public Integer getEmergencyPhone() {
		return this.emergencyPhone;
	}

	public void setEmergencyPhone(Integer emergencyPhone) {
		this.emergencyPhone = emergencyPhone;
	}

	public String getDateOfRegistration() {
		return this.dateOfRegistration;
	}

	public void setDateOfRegistration(String dateOfRegistration) {
		this.dateOfRegistration = dateOfRegistration;
	}

	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	public Integer getFamilyRelationFamilyId() {
		return this.familyRelationFamilyId;
	}

	public void setFamilyRelationFamilyId(Integer familyRelationFamilyId) {
		this.familyRelationFamilyId = familyRelationFamilyId;
	}

}
