package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Userstatus generated by hbm2java
 */
public class Userstatus implements java.io.Serializable {

	private int statusId;
	private String status;

	public Userstatus() {
	}

	public Userstatus(int statusId) {
		this.statusId = statusId;
	}

	public Userstatus(int statusId, String status) {
		this.statusId = statusId;
		this.status = status;
	}

	public int getStatusId() {
		return this.statusId;
	}

	public void setStatusId(int statusId) {
		this.statusId = statusId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
