package mprofile.core.entity;
// Generated Sep 25, 2016 11:30:02 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Usertype generated by hbm2java
 */
public class Usertype implements java.io.Serializable {

	private int userTypeId;
	private String userType;
	private String description;

	public Usertype() {
	}

	public Usertype(int userTypeId, String userType) {
		this.userTypeId = userTypeId;
		this.userType = userType;
	}

	public Usertype(int userTypeId, String userType, String description) {
		this.userTypeId = userTypeId;
		this.userType = userType;
		this.description = description;
	}

	public int getUserTypeId() {
		return this.userTypeId;
	}

	public void setUserTypeId(int userTypeId) {
		this.userTypeId = userTypeId;
	}

	public String getUserType() {
		return this.userType;
	}

	public void setUserType(String userType) {
		this.userType = userType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
