package mprofile.core.entity;
// Generated Sep 23, 2016 5:09:00 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Visitappointmentschedule generated by hbm2java
 */
public class Visitappointmentschedule implements java.io.Serializable {

	private int appointmentId;
	private String date;
	private String time;
	private Integer delay;
	private int estimationDuration;
	private int actualDuration;
	private Integer emrId;
	private Integer doctorId;
	private int hospitalId;
	private int caseId;
	private String causeDescription;

	public Visitappointmentschedule() {
	}

	public Visitappointmentschedule(int appointmentId, int estimationDuration, int actualDuration, int hospitalId,
			int caseId) {
		this.appointmentId = appointmentId;
		this.estimationDuration = estimationDuration;
		this.actualDuration = actualDuration;
		this.hospitalId = hospitalId;
		this.caseId = caseId;
	}

	public Visitappointmentschedule(int appointmentId, String date, String time, Integer delay, int estimationDuration,
			int actualDuration, Integer emrId, Integer doctorId, int hospitalId, int caseId, String causeDescription) {
		this.appointmentId = appointmentId;
		this.date = date;
		this.time = time;
		this.delay = delay;
		this.estimationDuration = estimationDuration;
		this.actualDuration = actualDuration;
		this.emrId = emrId;
		this.doctorId = doctorId;
		this.hospitalId = hospitalId;
		this.caseId = caseId;
		this.causeDescription = causeDescription;
	}

	public int getAppointmentId() {
		return this.appointmentId;
	}

	public void setAppointmentId(int appointmentId) {
		this.appointmentId = appointmentId;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public String getTime() {
		return this.time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getDelay() {
		return this.delay;
	}

	public void setDelay(Integer delay) {
		this.delay = delay;
	}

	public int getEstimationDuration() {
		return this.estimationDuration;
	}

	public void setEstimationDuration(int estimationDuration) {
		this.estimationDuration = estimationDuration;
	}

	public int getActualDuration() {
		return this.actualDuration;
	}

	public void setActualDuration(int actualDuration) {
		this.actualDuration = actualDuration;
	}

	public Integer getEmrId() {
		return this.emrId;
	}

	public void setEmrId(Integer emrId) {
		this.emrId = emrId;
	}

	public Integer getDoctorId() {
		return this.doctorId;
	}

	public void setDoctorId(Integer doctorId) {
		this.doctorId = doctorId;
	}

	public int getHospitalId() {
		return this.hospitalId;
	}

	public void setHospitalId(int hospitalId) {
		this.hospitalId = hospitalId;
	}

	public int getCaseId() {
		return this.caseId;
	}

	public void setCaseId(int caseId) {
		this.caseId = caseId;
	}

	public String getCauseDescription() {
		return this.causeDescription;
	}

	public void setCauseDescription(String causeDescription) {
		this.causeDescription = causeDescription;
	}

}
